java -jar baksmali-2.2.7.jar d --di false -o android-support-v7-recyclerview .\framework\vdexExtractor_deodexed\android-support-v7-recyclerview\android-support-v7-recyclerview_classes.dex.dex
java -jar baksmali-2.2.7.jar d --di false -o android-support-v13 .\framework\vdexExtractor_deodexed\android-support-v13\android-support-v13_classes.dex.dex
java -jar baksmali-2.2.7.jar d --di false -o boot-framework .\framework\vdexExtractor_deodexed\boot-framework\boot-framework_classes.dex
java -jar baksmali-2.2.7.jar d --di false -o boot-framework2 .\framework\vdexExtractor_deodexed\boot-framework\boot-framework_classes2.dex
java -jar baksmali-2.2.7.jar d --di false -o boot-framework3 .\framework\vdexExtractor_deodexed\boot-framework\boot-framework_classes3.dex
java -jar baksmali-2.2.7.jar d --di false -o boot-miui .\framework\vdexExtractor_deodexed\boot-miui\boot-miui_classes.dex
java -jar baksmali-2.2.7.jar d --di false -o boot-miuisystem .\framework\vdexExtractor_deodexed\boot-miuisystem\boot-miuisystem_classes.dex
java -jar baksmali-2.2.7.jar d --di false -o gson .\framework\vdexExtractor_deodexed\gson\gson_classes.dex.dex
java -jar baksmali-2.2.7.jar d --di false -o volley .\framework\vdexExtractor_deodexed\volley\volley_classes.dex.dex
java -jar baksmali-2.2.7.jar d --di false -o zxing .\framework\vdexExtractor_deodexed\zxing\zxing_classes.dex.dex